SELECT * FROM CLIENTES;
SELECT * FROM PRODUCTOS;
SELECT * FROM PEDIDOS ORDER BY IMPORTE_TOTAL DESC;
SELECT * FROM PRODUCTO_PROVEEDOR;
SELECT * FROM PROVEEDORES;
SELECT * FROM LINEAS_PEDIDO;
SELECT COUNT(*) FROM LINEAS_PEDIDO;

select * from productos where precio > 1;

 
-- 1. PEDIDOS REALIZADOS EL 2025-04-14
SELECT * FROM PEDIDOS WHERE FECHA = '2025-04-14';


-- 2. PEDIDOS DEL CLIENTE CON ID 37
SELECT * FROM PEDIDOS WHERE ID_CLIENTE = 37;

-- 3. SUMAR EL IMPORTE TOTAL 
SELECT SUM(IMPORTE_TOTAL) FROM PEDIDOS;

-- 4. TIPOS DE ESTADO DE PEDIDOS
SELECT DISTINCT ESTADO FROM PEDIDOS;

-- 5. PEDIDOS CON ESTADO ENVIADO
SELECT * FROM PEDIDOS WHERE ESTADO = 'Enviado';

-- 6. TODOS LOS PRODUCTOS PERTENECIENTES A UNA DETERMINADA CATEGORÍA
SELECT * FROM PRODUCTOS WHERE CATEGORIA = 'Electronica';

-- 7.
EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM PEDIDOS WHERE ESTADO = 'Enviado';
EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM PEDIDOS WHERE FECHA = '2025-04-14';
EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM PEDIDOS WHERE ID_CLIENTE = 37;
EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM PEDIDOS WHERE ID_PEDIDO = 123456;

SELECT * FROM CLIENTES C JOIN PEDIDOS P 
ON C.ID_CLIENTE = P.ID_CLIENTE;


SELECT MIN(importe_total), MAX(importe_total), AVG(importe_total)









